# Generated by Django 5.1.7 on 2025-06-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_dietary_app', '0002_rename_ingredient_ingredientfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(default='g', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredientfact',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ingredientfact',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientfact',
            name='cholesterol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientfact',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientfact',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientfact',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientfact',
            name='saturated_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientfact',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientfact',
            name='total_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_facts', to='food_dietary_app.ingredientfact')),
                ('nutrient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dietary_app.nutrienttype')),
            ],
            options={
                'unique_together': {('ingredient', 'nutrient_type')},
            },
        ),
    ]
