# Generated by Django 5.1.7 on 2025-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_dietary_app', '0003_nutrienttype_alter_ingredientfact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientfact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientfact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
