# Generated by Django 5.1.7 on 2025-03-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_dietary_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='IngredientFact',
        ),
    ]
